{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f543eb80",
   "metadata": {},
   "source": [
    "### 32969번"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "031fc51f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "digital humanities\n",
      "public bigdata\n"
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m현재 셀 또는 이전 셀에서 코드를 실행하는 동안 Kernel이 충돌했습니다. \n",
      "\u001b[1;31m셀의 코드를 검토하여 가능한 오류 원인을 식별하세요. \n",
      "\u001b[1;31m자세한 내용을 보려면 <a href='https://aka.ms/vscodeJupyterKernelCrash'>여기</a>를 클릭하세요. \n",
      "\u001b[1;31m자세한 내용은 Jupyter <a href='command:jupyter.viewOutput'>로그</a>를 참조하세요."
     ]
    }
   ],
   "source": [
    "digital_humanities = [\"social\", \"history\", \"language\", \"literacy\"]\n",
    "topic = input()\n",
    "\n",
    "for i in digital_humanities:\n",
    "    if i in topic:\n",
    "        print(\"digital humanities\")\n",
    "        exit(0)\n",
    "\n",
    "print(\"public bigdata\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a734720f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7dbb6129",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
